# Generated by Django 3.1.2 on 2021-01-07 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210106_1904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postmodels',
            name='cover',
        ),
        migrations.AddField(
            model_name='postmodels',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
