# Generated by Django 3.1.2 on 2021-01-07 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210107_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodels',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
