# Generated by Django 3.1.2 on 2021-01-07 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_postmodels_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodels',
            name='slug',
            field=models.SlugField(blank=True, editable=False),
        ),
    ]
