# Generated by Django 3.1.2 on 2021-01-14 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20210114_2021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postmodels',
            name='foto',
        ),
    ]
