# Generated by Django 3.1.2 on 2021-01-20 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_remove_postmodels_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodels',
            name='isi_penutup',
            field=models.TextField(default='content', max_length=370),
        ),
        migrations.AlterField(
            model_name='postmodels',
            name='judul_content1_kata_belakang',
            field=models.CharField(default='content', max_length=35),
        ),
        migrations.AlterField(
            model_name='postmodels',
            name='judul_content1_kata_depan',
            field=models.CharField(default='content', max_length=23),
        ),
        migrations.AlterField(
            model_name='postmodels',
            name='judul_content2_kata_belakang',
            field=models.CharField(default='content', max_length=15),
        ),
        migrations.AlterField(
            model_name='postmodels',
            name='judul_content2_kata_depan',
            field=models.CharField(default='content', max_length=15),
        ),
        migrations.AlterField(
            model_name='postmodels',
            name='judul_latarbelakang',
            field=models.CharField(default='content', max_length=12),
        ),
        migrations.AlterField(
            model_name='postmodels',
            name='judul_penutup_kata_belakang',
            field=models.CharField(default='content', max_length=18),
        ),
        migrations.AlterField(
            model_name='postmodels',
            name='judul_penutup_kata_depan',
            field=models.CharField(default='content', max_length=18),
        ),
        migrations.AlterField(
            model_name='postmodels',
            name='judulkatabelakang',
            field=models.CharField(default='content', max_length=11),
        ),
        migrations.AlterField(
            model_name='postmodels',
            name='judulkatadepan',
            field=models.CharField(default='content', max_length=11),
        ),
        migrations.AlterField(
            model_name='postmodels',
            name='nama',
            field=models.CharField(max_length=28),
        ),
    ]
