# Generated by Django 3.1.2 on 2021-01-21 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20210120_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodels',
            name='nama',
            field=models.CharField(max_length=30),
        ),
    ]
