# Generated by Django 3.1.2 on 2021-01-21 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20210121_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodels',
            name='isi_latarbelakang',
            field=models.TextField(default='content', max_length=340),
        ),
        migrations.AlterField(
            model_name='postmodels',
            name='judulkatabelakang',
            field=models.CharField(default='content', max_length=13),
        ),
        migrations.AlterField(
            model_name='postmodels',
            name='judulkatadepan',
            field=models.CharField(default='content', max_length=13),
        ),
    ]
