# Generated by Django 3.1.2 on 2021-01-22 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20210121_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodels',
            name='isi_penutup',
            field=models.TextField(default='content', max_length=380),
        ),
    ]
