# Generated by Django 3.1.2 on 2021-01-24 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20210122_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodels',
            name='category',
            field=models.CharField(default='Pahlawan', max_length=50),
        ),
    ]
