# Generated by Django 3.1.2 on 2021-01-25 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20210125_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodels',
            name='isi_content2',
            field=models.TextField(default='content', max_length=500),
        ),
        migrations.AlterField(
            model_name='postmodels',
            name='isi_penutup',
            field=models.TextField(default='content', max_length=600),
        ),
    ]
