# Generated by Django 3.1.2 on 2021-01-26 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_auto_20210125_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodels',
            name='judul_content2_kata_belakang',
            field=models.CharField(default='content', max_length=18),
        ),
    ]
