# Generated by Django 3.1.2 on 2021-01-27 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_auto_20210126_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodels',
            name='isi_content2',
            field=models.TextField(default='content', max_length=335),
        ),
    ]
