# Generated by Django 3.1.2 on 2021-01-27 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_auto_20210127_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodels',
            name='judul_latarbelakang',
            field=models.CharField(default='content', max_length=15),
        ),
    ]
